parameters: {}
environment: {}
packages:
    - name: test
      shared: false
      environment:
            DB_URI: "${DB_URI}"
      actions:
        - name: checkConnection
      parameters: {}
      annotations: {}