parameters: {}
environment: {}
packages:
    - name: test
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: check
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          parameters: {}
          environment: 
            MONGODB_USERNAME: "${MONGODB_USERNAME}"
            MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
            MONGODB_CLUSTER: "${MONGODB_CLUSTER}"
          annotations: {}
          limits: {}