parameters: {}
environment:
  DB_URI: "${DB_URI}"
packages:
    - name: test
      shared: false
      environment:
            DB_URI: "${DB_URI}"
      functions:
        - name: checkConnection
          environment:
            DB_URI: "${DB_URI}"